# Generated by Django 2.0 on 2018-09-04 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('SL', 'SOLO'), ('TN', 'TINY'), ('LT', 'LITTLE'), ('SM', 'SMALL'), ('SM', 'SMALLISH'), ('MD', 'MEDIUM'), ('LG', 'LARGEISH'), ('CE', 'CORPORATE_ENTITY')], default=(6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25), max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 959687)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 959772)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 959623)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_contacted',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 959407)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 959499)),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 966788)),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 966853)),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 966693)),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='first_contacted',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 966194)),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='last_contacted',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 22, 35, 28, 966291)),
        ),
    ]
