# Generated by Django 2.0 on 2018-08-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfw', '0002_remove_jobapp_jobapp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='jobapp_name',
            field=models.TextField(default='nullabledefault'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='company',
            field=models.TextField(default='nullabledefault'),
        ),
    ]
