# Generated by Django 2.0 on 2018-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfw', '0004_auto_20180904_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('SL', 'SOLO'), ('TN', 'TINY'), ('LT', 'LITTLE'), ('SM', 'SMALL'), ('SM', 'SMALLISH'), ('MD', 'MEDIUM'), ('LG', 'LARGEISH'), ('CE', 'CORPORATE_ENTITY')], default=(6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25), max_length=2),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='pipeline_status',
            field=models.CharField(choices=[('PS', 'PROSPECT'), ('RO', 'REACHEDOUT'), ('QD', 'QUALIFIED'), ('SN', 'SCREENING')], default=(0, 1, 2, 3, 4, 5), max_length=2),
        ),
    ]
